// flow-typed signature: c047b2df2508407c764085c93d5df72b
// flow-typed version: <<STUB>>/@jest/globals_v^28/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jest/globals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jest/globals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jest/globals/build' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jest/globals/build/index' {
  declare module.exports: $Exports<'@jest/globals/build'>;
}
declare module '@jest/globals/build/index.js' {
  declare module.exports: $Exports<'@jest/globals/build'>;
}
