// flow-typed signature: 5e19e1f5a0bf6885c46cc11354154481
// flow-typed version: <<STUB>>/jest_v^28/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest/bin/jest' {
  declare module.exports: any;
}

declare module 'jest/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest/bin/jest.js' {
  declare module.exports: $Exports<'jest/bin/jest'>;
}
declare module 'jest/build/index' {
  declare module.exports: $Exports<'jest/build'>;
}
declare module 'jest/build/index.js' {
  declare module.exports: $Exports<'jest/build'>;
}
