// flow-typed signature: 4cfbe4fc0c6876cb733d644686deb6e5
// flow-typed version: <<STUB>>/nock_v^13/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nock/lib/back' {
  declare module.exports: any;
}

declare module 'nock/lib/common' {
  declare module.exports: any;
}

declare module 'nock/lib/global_emitter' {
  declare module.exports: any;
}

declare module 'nock/lib/intercept' {
  declare module.exports: any;
}

declare module 'nock/lib/intercepted_request_router' {
  declare module.exports: any;
}

declare module 'nock/lib/interceptor' {
  declare module.exports: any;
}

declare module 'nock/lib/match_body' {
  declare module.exports: any;
}

declare module 'nock/lib/playback_interceptor' {
  declare module.exports: any;
}

declare module 'nock/lib/recorder' {
  declare module.exports: any;
}

declare module 'nock/lib/scope' {
  declare module.exports: any;
}

declare module 'nock/lib/socket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nock/index' {
  declare module.exports: $Exports<'nock'>;
}
declare module 'nock/index.js' {
  declare module.exports: $Exports<'nock'>;
}
declare module 'nock/lib/back.js' {
  declare module.exports: $Exports<'nock/lib/back'>;
}
declare module 'nock/lib/common.js' {
  declare module.exports: $Exports<'nock/lib/common'>;
}
declare module 'nock/lib/global_emitter.js' {
  declare module.exports: $Exports<'nock/lib/global_emitter'>;
}
declare module 'nock/lib/intercept.js' {
  declare module.exports: $Exports<'nock/lib/intercept'>;
}
declare module 'nock/lib/intercepted_request_router.js' {
  declare module.exports: $Exports<'nock/lib/intercepted_request_router'>;
}
declare module 'nock/lib/interceptor.js' {
  declare module.exports: $Exports<'nock/lib/interceptor'>;
}
declare module 'nock/lib/match_body.js' {
  declare module.exports: $Exports<'nock/lib/match_body'>;
}
declare module 'nock/lib/playback_interceptor.js' {
  declare module.exports: $Exports<'nock/lib/playback_interceptor'>;
}
declare module 'nock/lib/recorder.js' {
  declare module.exports: $Exports<'nock/lib/recorder'>;
}
declare module 'nock/lib/scope.js' {
  declare module.exports: $Exports<'nock/lib/scope'>;
}
declare module 'nock/lib/socket.js' {
  declare module.exports: $Exports<'nock/lib/socket'>;
}
