// flow-typed signature: 06b9d65ab1bba78a80a29fdde0a49b31
// flow-typed version: <<STUB>>/process-exists_v^4.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'process-exists'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'process-exists' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'process-exists/index' {
  declare module.exports: $Exports<'process-exists'>;
}
declare module 'process-exists/index.js' {
  declare module.exports: $Exports<'process-exists'>;
}
