// flow-typed signature: 7fe7659f9fd557c443fc226c4daef451
// flow-typed version: <<STUB>>/rmfr_v^2.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rmfr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rmfr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rmfr/index' {
  declare module.exports: $Exports<'rmfr'>;
}
declare module 'rmfr/index.js' {
  declare module.exports: $Exports<'rmfr'>;
}
